FROM node:20-alpine AS client_builder2

WORKDIR /app

COPY ./client/package*.json ./

RUN npm install

COPY ./client /app

RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY ./server/package*.json ./

RUN npm install

COPY ./server /app

COPY --from=client_builder2 /app/dist /app/public

CMD ["node", "server.js"]


