FROM node:20-alpine AS clent_builder

WORKDIR /app

COPY ./client/package*.json ./

RUN npm install

COPY ./client /app

RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY ./server/package*.json ./

RUN npm install

COPY ./server /app

COPY --from=clent_builder /app/dist /app/public

CMD ["node", "server.js"]
